general {
    immediate_render = true
    hide_cursor = true
}

animations {
    enabled = false
}

background {
    monitor =
    path = ~/dotfiles/wallpaper.jpg
    blur_passes = 2
    blur_size = 8
    brightness = 0.5
}

shape {
    monitor =
    size = 1024, 768
    color = rgba(48, 52, 70, 0.75)
    position = 0, 0
}

input-field {
    monitor =
    size = 200, 30
    outline_thickness = 2

    outer_color = rgba(166, 209, 137, 1)
    inner_color = rgba(0, 0, 0, 0)
    font_color = rgb(198, 208, 245)

    fade_on_empty = false
    placeholder_text = Password
}
